services:

  ualflix_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ualflix
    networks:
      - ualflix_network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  catalog_service:
    build: ./catalog_service
    depends_on:
      - ualflix_db
      - queue_service
    networks:
      - ualflix_network
    volumes:
      - video_storage:/videos

  authentication_service:
    build: ./authentication_service
    depends_on:
      - ualflix_db
      - queue_service
    networks:
      - ualflix_network

  streaming_service:
    build: ./streaming_service
    volumes:
      - video_storage:/videos
    networks:
      - ualflix_network

  video_processor:
    build: ./video_processor
    depends_on:
      - queue_service
    networks:
      - ualflix_network
    volumes:
      - video_storage:/videos

  queue_service:
    image: rabbitmq:3-management
    networks:
      - ualflix_network
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ualflix
      - RABBITMQ_DEFAULT_PASS=ualflix_password

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Adicionado mapeamento de porta para o frontend
    networks:
      - ualflix_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - video_storage:/videos
    depends_on:
      - frontend
      - catalog_service
      - streaming_service
    networks:
      - ualflix_network

  # Prometheus para coleta de métricas
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ualflix_network
    depends_on:
      - catalog_service
      - streaming_service

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:4000"  
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - ualflix_network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=4000 

volumes:
  db_data:
  video_storage:
  grafana_data:

networks:
  ualflix_network:
    driver: bridge