apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: ualflix
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  type: ClusterIP
