apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: ualflix
  labels:
    app: admin-service
    tier: backend
    component: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
        tier: backend
        component: admin
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: mongo:6.0
        command: ['sh', '-c']
        args:
        - |
          until mongosh --host mongodb-0.mongodb-headless.ualflix.svc.cluster.local --eval "db.adminCommand('ping')" >/dev/null 2>&1; do
            echo "Waiting for MongoDB..."
            sleep 2
          done
          echo "MongoDB ready!"
      containers:
      - name: admin-service
        image: admin_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb://admin:password@mongodb-0.mongodb-headless.ualflix.svc.cluster.local:27017,mongodb-1.mongodb-headless.ualflix.svc.cluster.local:27017,mongodb-2.mongodb-headless.ualflix.svc.cluster.local:27017/ualflix?replicaSet=ualflix-replica-set&authSource=admin"
        - name: MONGODB_DATABASE
          value: "ualflix"
        - name: MONGODB_USERNAME
          value: "admin"
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-password
        - name: MONGODB_REPLICA_SET
          value: "ualflix-replica-set"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8000"
        - name: CATALOG_SERVICE_URL
          value: "http://catalog-service:8000"
        - name: STREAMING_SERVICE_URL
          value: "http://streaming-service:8001"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 45
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 15
          periodSeconds: 5