apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: ualflix
spec:
  selector:
    app: admin-service
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  type: ClusterIP
