apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ualflix
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP
