apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  namespace: ualflix
spec:
  selector:
    app: streaming-service
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  type: ClusterIP
