apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: ualflix
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: prometheus
  type: ClusterIP
