global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'catalog_service'
    static_configs:
      - targets: ['catalog_service:8000']

  - job_name: 'streaming_service'
    static_configs:
      - targets: ['streaming_service:8001']

  - job_name: 'video_processor'
    static_configs:
      - targets: ['video_processor:9102']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['queue_service:15672']