apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ualflix
  labels:
    app: ualflix
    component: secrets
type: Opaque
data:
  mongodb-root-password: cGFzc3dvcmQ=
  mongodb-username: YWRtaW4=
  mongodb-password: cGFzc3dvcmQ=
  mongodb-database: dWFsZmxpeA==
  rabbitmq-password: dWFsZmxpeF9wYXNzd29yZA==
  jwt-secret: dWFsZmxpeC1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ualflix
  labels:
    app: ualflix
    component: config
data:
  MONGODB_SERVICE: "mongodb-headless"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "ualflix"
  MONGODB_USERNAME: "admin"
  MONGODB_REPLICA_SET: "ualflix-replica-set"
  QUEUE_HOST: "rabbitmq-service"
  QUEUE_USER: "ualflix"
  AUTH_SERVICE_URL: "http://auth-service:8000"
  CATALOG_SERVICE_URL: "http://catalog-service:8000"
  STREAMING_SERVICE_URL: "http://streaming-service:8001"
  ADMIN_SERVICE_URL: "http://admin-service:8002"
  VIDEO_PROCESSOR_URL: "http://video-processor-service:8000"
  NGINX_GATEWAY_URL: "http://nginx-gateway:8080"
  FLASK_ENV: "development"
  FLASK_DEBUG: "1"
  LOG_LEVEL: "INFO"