apiVersion: v1
kind: Service
metadata:
  name: video-processor-service
  namespace: ualflix
spec:
  selector:
    app: video-processor
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
